#!/usr/bin/env python3
"""Add international visualization cells to the legacy analysis notebook"""

import json

# Read existing notebook
with open('analysis.ipynb', 'r') as f:
    nb = json.load(f)

# New cells to add
new_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "\n",
            "# INTERNATIONAL POLICY COMPARISONS\n",
            "\n",
            "**Purpose**: Visualize how other countries solved the startup funding gap\n",
            "\n",
            "**Key Programs**:\n",
            "- **Israel Yozma (1993)**: Government co-invested in VC funds with foreign partners + buyout option → 60x VC growth\n",
            "- **UK SEIS/EIS (1994/2012)**: 30-50% tax relief for angel investors → 90%+ of angel deals use it\n",
            "- **Singapore SEEDS (2017)**: Co-investment with private VCs → #4 global ecosystem\n",
            "\n",
            "**Three visualization options below** - evaluate which tells the story best.\n",
            "\n",
            "---\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# === INTERNATIONAL VISUALIZATIONS SETUP ===\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.patches as mpatches\n",
            "import numpy as np\n",
            "import os\n",
            "\n",
            "# Okabe-Ito colorblind-friendly palette\n",
            "COLORS = {\n",
            "    'orange': '#E69F00',\n",
            "    'skyblue': '#56B4E9',\n",
            "    'green': '#009E73',\n",
            "    'yellow': '#F0E442',\n",
            "    'blue': '#0072B2',\n",
            "    'vermillion': '#D55E00',\n",
            "    'purple': '#CC79A7',\n",
            "    'black': '#000000',\n",
            "    'gray': '#999999'\n",
            "}\n",
            "\n",
            "def tufte_style(ax):\n",
            "    \"\"\"Apply Tufte minimalist styling to axis\"\"\"\n",
            "    ax.spines['top'].set_visible(False)\n",
            "    ax.spines['right'].set_visible(False)\n",
            "    ax.spines['left'].set_color('#666666')\n",
            "    ax.spines['bottom'].set_color('#666666')\n",
            "    ax.spines['left'].set_linewidth(0.5)\n",
            "    ax.spines['bottom'].set_linewidth(0.5)\n",
            "    ax.tick_params(colors='#666666', width=0.5)\n",
            "    ax.grid(False)\n",
            "    return ax\n",
            "\n",
            "os.makedirs('figures', exist_ok=True)\n",
            "print('Setup complete')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Option 1: Slope Chart (Israel Transformation Story)\n",
            "\n",
            "**Best for**: Showing dramatic before/after transformation\n",
            "**Narrative**: \"Look what one program did for Israel\"\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# OPTION 1: Slope Chart - Israel Transformation\n",
            "fig, ax = plt.subplots(figsize=(10, 7))\n",
            "tufte_style(ax)\n",
            "\n",
            "# Data: VC investment before and after Yozma\n",
            "countries = ['Israel', 'Netherlands']\n",
            "before = [58, 50]     # 1993 (millions USD)\n",
            "after = [3300, 200]   # 2000 (millions USD)\n",
            "\n",
            "# Position on x-axis\n",
            "x_before, x_after = 0, 1\n",
            "\n",
            "for i, (country, b, a) in enumerate(zip(countries, before, after)):\n",
            "    color = COLORS['green'] if country == 'Israel' else COLORS['vermillion']\n",
            "    lw = 3 if country == 'Israel' else 2\n",
            "    \n",
            "    # Plot line\n",
            "    ax.plot([x_before, x_after], [b, a], color=color, linewidth=lw, marker='o', markersize=10)\n",
            "    \n",
            "    # Labels\n",
            "    ax.text(x_before - 0.08, b, f'${b}M', ha='right', va='center', fontsize=11, color=color, fontweight='bold')\n",
            "    ax.text(x_after + 0.08, a, f'${a:,}M', ha='left', va='center', fontsize=11, color=color, fontweight='bold')\n",
            "    \n",
            "    # Country name\n",
            "    if country == 'Israel':\n",
            "        ax.text(0.5, (b + a) / 2 + 500, country, ha='center', va='bottom', fontsize=12, color=color, fontweight='bold')\n",
            "        ax.text(0.5, (b + a) / 2 + 200, '60x growth', ha='center', va='top', fontsize=10, color=color, style='italic')\n",
            "    else:\n",
            "        ax.text(0.5, (b + a) / 2 - 100, country, ha='center', va='top', fontsize=12, color=color, fontweight='bold')\n",
            "        ax.text(0.5, (b + a) / 2 - 350, '4x growth', ha='center', va='top', fontsize=10, color=color, style='italic')\n",
            "\n",
            "# Yozma annotation\n",
            "ax.annotate('Yozma Program\\n(1993)', xy=(0.15, 100), fontsize=10, color=COLORS['green'],\n",
            "            bbox=dict(boxstyle='round,pad=0.3', facecolor='#E8F5E9', edgecolor=COLORS['green']))\n",
            "\n",
            "ax.set_xlim(-0.3, 1.3)\n",
            "ax.set_ylim(-200, 4000)\n",
            "ax.set_xticks([0, 1])\n",
            "ax.set_xticklabels(['1993\\n(Before Yozma)', '2000\\n(After Yozma)'], fontsize=11)\n",
            "ax.set_ylabel('Annual VC Investment ($ millions)', fontsize=11)\n",
            "ax.set_title(\"Israel solved the scale-up gap—Netherlands hasn't (yet)\", fontsize=14, fontweight='bold', loc='left', pad=20)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('figures/intl_option1_slope.png', dpi=150, bbox_inches='tight', facecolor='white')\n",
            "plt.show()\n",
            "\n",
            "print(\"\\n✓ Option 1: Slope chart emphasizes Israel's dramatic 60x transformation\")\n",
            "print(\"  Pros: Simple, dramatic, memorable\")\n",
            "print(\"  Cons: Only shows one success story (Israel)\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Option 2: Dumbbell Chart (Gap Analysis)\n",
            "\n",
            "**Best for**: Showing where NL needs to improve across multiple metrics\n",
            "**Narrative**: \"Here's what we need to close\"\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# OPTION 2: Dumbbell Chart - Gap Analysis\n",
            "fig, ax = plt.subplots(figsize=(11, 6))\n",
            "tufte_style(ax)\n",
            "\n",
            "# Data: NL vs Best Practice\n",
            "metrics = ['Seed→Series A\\nConversion', 'Scale-up\\nRatio', 'Local Funding\\nShare', 'ESOP\\nRanking']\n",
            "nl_values = [6.2, 21.5, 22, 25]  # Netherlands (ESOP as percentile)\n",
            "best_values = [21.4, 54, 78, 90]  # Best practice (Israel/USA)\n",
            "best_labels = ['Israel', 'USA', 'USA', 'Israel']\n",
            "\n",
            "y_pos = np.arange(len(metrics))\n",
            "\n",
            "# Draw dumbbells\n",
            "for i, (metric, nl, best, best_lbl) in enumerate(zip(metrics, nl_values, best_values, best_labels)):\n",
            "    # Connecting line (the gap)\n",
            "    ax.plot([nl, best], [i, i], color=COLORS['gray'], linewidth=2, zorder=1)\n",
            "    \n",
            "    # NL dot\n",
            "    ax.scatter(nl, i, s=150, color=COLORS['vermillion'], zorder=2, edgecolors='white', linewidths=1.5)\n",
            "    ax.text(nl, i + 0.25, f'{nl}%', ha='center', va='bottom', fontsize=10, color=COLORS['vermillion'], fontweight='bold')\n",
            "    \n",
            "    # Best practice dot\n",
            "    ax.scatter(best, i, s=150, color=COLORS['green'], zorder=2, edgecolors='white', linewidths=1.5)\n",
            "    ax.text(best, i + 0.25, f'{best}%', ha='center', va='bottom', fontsize=10, color=COLORS['green'], fontweight='bold')\n",
            "    \n",
            "    # Gap label\n",
            "    gap = best - nl\n",
            "    ax.text((nl + best) / 2, i - 0.25, f'Gap: {gap:.0f}pp', ha='center', va='top', fontsize=9, color=COLORS['gray'], style='italic')\n",
            "\n",
            "# Legend\n",
            "nl_patch = mpatches.Patch(color=COLORS['vermillion'], label='Netherlands')\n",
            "best_patch = mpatches.Patch(color=COLORS['green'], label='Best Practice (Israel/USA)')\n",
            "ax.legend(handles=[nl_patch, best_patch], loc='lower right', fontsize=10, frameon=False)\n",
            "\n",
            "ax.set_yticks(y_pos)\n",
            "ax.set_yticklabels(metrics, fontsize=11)\n",
            "ax.set_xlim(0, 100)\n",
            "ax.set_xlabel('Percentage', fontsize=11)\n",
            "ax.set_title('The gaps Netherlands needs to close', fontsize=14, fontweight='bold', loc='left', pad=20)\n",
            "ax.invert_yaxis()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('figures/intl_option2_dumbbell.png', dpi=150, bbox_inches='tight', facecolor='white')\n",
            "plt.show()\n",
            "\n",
            "print(\"\\n✓ Option 2: Dumbbell chart shows multiple gaps simultaneously\")\n",
            "print(\"  Pros: Comprehensive, shows multiple improvement areas\")\n",
            "print(\"  Cons: More complex, less narrative punch\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Option 3: Timeline Chart (Policy Interventions)\n",
            "\n",
            "**Best for**: Showing sequence of successful policies over time\n",
            "**Narrative**: \"Here's what worked and when\"\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# OPTION 3: Timeline - Policy Interventions\n",
            "fig, ax = plt.subplots(figsize=(12, 5))\n",
            "tufte_style(ax)\n",
            "\n",
            "# Policy milestones\n",
            "policies = [\n",
            "    (1993, 'Israel', 'Yozma Program', '60x VC growth\\nby 2000', COLORS['green']),\n",
            "    (1994, 'UK', 'EIS Launched', '30% tax relief\\nfor investors', COLORS['blue']),\n",
            "    (2012, 'UK', 'SEIS Added', '50% tax relief\\n90%+ angel deals', COLORS['skyblue']),\n",
            "    (2017, 'Singapore', 'SEEDS Capital', '#4 global\\nby 2025', COLORS['orange']),\n",
            "    (2024, 'Netherlands', 'Current State', '6.2% Seed→A\\n(Gap to close)', COLORS['vermillion']),\n",
            "]\n",
            "\n",
            "# Draw timeline\n",
            "ax.axhline(y=0, color=COLORS['gray'], linewidth=1, zorder=1)\n",
            "\n",
            "for i, (year, country, program, outcome, color) in enumerate(policies):\n",
            "    # Vertical line\n",
            "    y_offset = 0.5 if i % 2 == 0 else -0.5\n",
            "    ax.plot([year, year], [0, y_offset * 0.8], color=color, linewidth=2)\n",
            "    \n",
            "    # Dot on timeline\n",
            "    ax.scatter(year, 0, s=100, color=color, zorder=2, edgecolors='white', linewidths=1.5)\n",
            "    \n",
            "    # Label box\n",
            "    ax.annotate(f'{country}\\n{program}\\n\\n{outcome}',\n",
            "                xy=(year, y_offset * 0.8),\n",
            "                ha='center', va='center' if y_offset > 0 else 'center',\n",
            "                fontsize=9, color=color, fontweight='bold',\n",
            "                bbox=dict(boxstyle='round,pad=0.4', facecolor='white', edgecolor=color, alpha=0.9))\n",
            "    \n",
            "    # Year label\n",
            "    ax.text(year, -0.15 if y_offset > 0 else 0.15, str(year), ha='center', va='top' if y_offset > 0 else 'bottom',\n",
            "            fontsize=10, fontweight='bold', color=COLORS['black'])\n",
            "\n",
            "ax.set_xlim(1990, 2027)\n",
            "ax.set_ylim(-1.2, 1.2)\n",
            "ax.set_title('Successful startup policies: A 30-year timeline', fontsize=14, fontweight='bold', loc='left', pad=20)\n",
            "ax.axis('off')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('figures/intl_option3_timeline.png', dpi=150, bbox_inches='tight', facecolor='white')\n",
            "plt.show()\n",
            "\n",
            "print(\"\\n✓ Option 3: Timeline shows policy sequence and outcomes\")\n",
            "print(\"  Pros: Shows proven playbook, includes NL current state\")\n",
            "print(\"  Cons: Doesn't show quantitative gap clearly\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "\n",
            "## Evaluation: Which Chart Works Best?\n",
            "\n",
            "| Option | Strength | Weakness | Best For |\n",
            "|--------|----------|----------|----------|\n",
            "| **1. Slope Chart** | Dramatic, memorable | Only shows Israel | Inspiring action |\n",
            "| **2. Dumbbell** | Comprehensive | Less emotional | Policy analysis |\n",
            "| **3. Timeline** | Shows playbook | Less quantitative | Historical context |\n",
            "\n",
            "### Recommendation\n",
            "\n",
            "**For the Ministry briefing**: Use **Option 3 (Timeline)** because:\n",
            "1. Shows a proven playbook (not just \"Israel did X\")\n",
            "2. Positions NL as \"next in sequence\" (call to action)\n",
            "3. Combines multiple success stories with NL's current state\n",
            "4. Policy-makers respond to \"here's what others did\" framing\n",
            "\n",
            "**Alternative**: Combine Option 1 (slope, for Israel deep-dive) with Option 2 (dumbbell, for comprehensive gaps) in an appendix.\n",
            "\n",
            "---\n"
        ]
    }
]

# Save updated notebook
with open('analysis.ipynb', 'w') as f:
    json.dump(nb, f, indent=2)

print(f"Added {len(new_cells)} cells to notebook")
print("Total cells now:", len(nb['cells']))
