version: 2

sources:
  - name: dealroom_raw
    description: Raw data from Dealroom daily NDJSON exports
    database: techleap_db
    schema: raw
    tables:
      - name: companies_raw
        description: Raw company records loaded from NDJSON
        columns:
          - name: company_id
            description: Unique identifier from Dealroom
            tests:
              - unique
              - not_null
          - name: name
            description: Company name
            tests:
              - not_null

models:
  - name: stg_companies
    description: |
      Staged company data with standardized field names, data types,
      and basic data quality filters applied.
    columns:
      - name: company_id
        description: Unique company identifier from source
        tests:
          - unique
          - not_null
      - name: company_name
        description: Cleaned company name
        tests:
          - not_null
      - name: founding_date
        description: Company founding date
      - name: employee_count
        description: Current employee count (if available)
      - name: total_funding_eur
        description: Total funding received in EUR
      - name: current_status
        description: Company operational status (operating, acquired, closed, ipo, unknown)
        tests:
          - accepted_values:
              values: ['operating', 'acquired', 'closed', 'ipo', 'unknown']
      - name: headquarters_city
        description: City of company headquarters
      - name: headquarters_country
        description: Country of company headquarters

  - name: stg_funding_rounds
    description: |
      Flattened funding rounds from company records.
      Each row represents a single funding event.
    columns:
      - name: company_id
        description: Reference to parent company
        tests:
          - not_null
      - name: round_type
        description: Normalized funding round type
        tests:
          - accepted_values:
              values: ['pre_seed', 'seed', 'series_a', 'series_b', 'series_c',
                       'series_d', 'series_e', 'series_f', 'series_g', 'series_h',
                       'growth', 'bridge', 'convertible_note', 'debt', 'grant',
                       'ipo', 'secondary', 'private_equity', 'unknown']
      - name: round_date
        description: Date of funding round
      - name: amount_eur
        description: Funding amount in EUR
      - name: round_sequence
        description: Sequential order of this round for the company
