version: 2

models:
  - name: mart_funding_analysis
    description: |
      Company-level funding analysis mart.
      Combines company attributes with aggregated funding metrics
      for ecosystem analysis and reporting.
    columns:
      - name: company_id
        description: Unique company identifier
        tests:
          - unique
          - not_null
      - name: company_name
        description: Company name
      - name: total_funding_rounds
        description: Total number of funding rounds received
      - name: total_funding_eur
        description: Total funding amount in EUR
      - name: funding_stage
        description: Current funding stage classification
        tests:
          - accepted_values:
              values: ['Pre-Funding', 'Seed Stage', 'Early Stage', 'Growth Stage', 'Late Stage', 'Other Funding']
      - name: first_funding_date
        description: Date of first funding round
      - name: last_funding_date
        description: Date of most recent funding round
      - name: latest_round_type
        description: Type of most recent funding round

  - name: mart_ecosystem_metrics
    description: |
      Ecosystem-level metrics aggregated by country and year.
      Used for Ministry briefings, State of Dutch Tech Report,
      and international benchmark comparisons.
    columns:
      - name: country
        description: Country name
        tests:
          - not_null
      - name: funding_year
        description: Year of first funding
        tests:
          - not_null
      - name: total_companies
        description: Count of companies that received funding
      - name: total_funding_eur
        description: Total funding in EUR
      - name: operating_rate
        description: Percentage of companies still operating
      - name: seed_to_series_a_rate
        description: Conversion rate from seed to Series A
      - name: yoy_company_growth
        description: Year-over-year growth in company count
      - name: yoy_funding_growth
        description: Year-over-year growth in funding volume
